**1. Load CSV,parquet,excel**

In [2]:
import os
import pandas as pd

**1. Load the CSV File**

In [3]:
df_csv = pd.read_csv("titanic.csv")

In [4]:
#Load selected columns

df_csv_subset= pd.read_csv(
    filepath_or_buffer="titanic.csv",
    usecols = ["Survived","Pclass","Age","Fare"]
)

df_csv_subset.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

**2. Read the Excel file**

In [5]:
df_excel = pd.read_excel("titanic.xlsx")

In [6]:
df_excel.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
df_excel_subset= pd.read_excel(
    io="titanic.xlsx",
    usecols = ["Survived","Pclass","Age","Fare"]
)

df_excel_subset.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [9]:
#Check sheet names
xls = pd.ExcelFile("titanic.xlsx")
print(xls.sheet_names)

['Sheet1']

In [10]:
df_excel_sheet = pd.read_excel("titanic.xlsx",sheet_name="Sheet1")

In [11]:
df_excel_sheet.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**3. Load the Parquet File**

In [12]:
df_paraquet = pd.read_parquet("titanic.parquet")
df_paraquet.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
#Load slected columns from Parquet

df_paraquet_subset = pd.read_parquet(
    "titanic.parquet",
    columns = ["Survived","Pclass","Age","Fare"]
)

df_paraquet_subset.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

**5.Load the CSV with different seperator**

In [16]:
df_tab = pd.read_csv("titanic_tab.csv",sep = "\t")
df_tab.shape

(891, 12)