In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
pd.set_option("display.max_columns",None)

In [4]:
df = pd.read_csv("titanic_dataset.csv")
print("Shape of the dataset:",df.shape)
print("Columns in the dataset:",df.columns.to_list())
df.head()

Shape of the dataset: (891, 15)
Columns in the dataset: ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [9]:
#Dropping "Alive" column as it is redundant due to the presence of "survived" column

df = df.drop(columns=["alive"])

In [10]:
print("Shape of the dataset:",df.shape)
print("Columns in the dataset:",df.columns.to_list())
df.head()

Shape of the dataset: (891, 14)
Columns in the dataset: ['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alone']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,True

In [12]:
target = "survived"

### **2. Drop Rows with Missing Target(Safe before train test split.)**

In [13]:
missing_target_count = df[target].isna().sum()
print("Rows with missing target value:",missing_target_count)

df = df.dropna(subset=[target])
print("Shape after dropping missing target rows",df.shape)

Rows with missing target value: 0
Shape after dropping missing target rows (891, 14)

### **3. Seperate x(features) and y(target)**

In [18]:
X = df.drop(columns=[target])
y = df[target]

print("X shape:",X.shape)
print("y shape:",y.shape)

X shape: (891, 13)
y shape: (891,)

In [24]:
print(X[:5])
print(y[:5])

   pclass     sex   age  sibsp  parch     fare embarked  class    who  \
0       3    male  22.0      1      0   7.2500        S  Third    man
1       1  female  38.0      1      0  71.2833        C  First  woman
2       3  female  26.0      0      0   7.9250        S  Third  woman
3       1  female  35.0      1      0  53.1000        S  First  woman
4       3    male  35.0      0      0   8.0500        S  Third    man

   adult_male deck  embark_town  alone
0        True  NaN  Southampton  False
1       False    C    Cherbourg  False
2       False  NaN  Southampton   True
3       False    C  Southampton  False
4        True  NaN  Southampton   True
0    0
1    1
2    1
3    1
4    0
Name: survived, dtype: int64

In [25]:
print("Target ditribution on full data:")
print(y.value_counts())

print("-" * 100)

print("Target distribution in percentage:")
print(y.value_counts(normalize=True).round(3))

Target ditribution on full data:
survived
0    549
1    342
Name: count, dtype: int64
----------------------------------------------------------------------------------------------------
Target distribution in percentage:
survived
0    0.616
1    0.384
Name: proportion, dtype: float64

**4. Train Test Split**
- Train Set -> ML Model Training
- Test Set -> ML Model Evaluation

X(features) -> training_features(X_train); test_features(X_test)

y(target)   -> training_targets(y_train); test_targets(y_test)

In [32]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size= 0.2,
    random_state= 42,
    stratify = y
)

print("Shapes:")
print("X:",X.shape)
print("y:",y.shape)
print("X_train:",X_train.shape)
print("X_test:",X_test.shape)
print("y_train:",y_train.shape)
print("y_test:",y_test.shape)

Shapes:
X: (891, 13)
y: (891,)
X_train: (712, 13)
X_test: (179, 13)
y_train: (712,)
y_test: (179,)

**Training Process**

- X_train, y_train -> ML Model Learns the pattern -> Trained ML Model

**Evaluation Process**

- X_test -> Trained ML Model -> y_pred(Output from the trained ML Model)
- Compare y_pred and y_test(True Labels)

In [36]:
print("Target distribution on full data:")
print(y.value_counts())

print("-" * 80)

print("Target distribution in Percentage:")
print(y.value_counts(normalize=True).round(3))

print("-" * 80)

print("Target distribution on training data:")
print(y_train.value_counts())

print("-" * 80)

print("Target distribution in Percentage:")
print(y_train.value_counts(normalize=True).round(3))

print("-" * 80)

print("Target distribution on test data:")
print(y_test.value_counts())

print("-" * 80)

print("Target distribution in Percentage:")
print(y_test.value_counts(normalize=True).round(3))

print("-" * 80)

Target distribution on full data:
survived
0    549
1    342
Name: count, dtype: int64
--------------------------------------------------------------------------------
Target distribution in Percentage:
survived
0    0.616
1    0.384
Name: proportion, dtype: float64
--------------------------------------------------------------------------------
Target distribution on training data:
survived
0    439
1    273
Name: count, dtype: int64
--------------------------------------------------------------------------------
Target distribution in Percentage:
survived
0    0.617
1    0.383
Name: proportion, dtype: float64
--------------------------------------------------------------------------------
Target distribution on test data:
survived
0    110
1     69
Name: count, dtype: int64
--------------------------------------------------------------------------------
Target distribution in Percentage:
survived
0    0.615
1    0.385
Name: proportion, dtype: float64
--------------------------------------------------------------------------------

**5. Save splits**

In [40]:
train_df = X_train.copy()
train_df[target] = y_train.values

test_df = X_test.copy()
test_df[target] = y_test.values

In [41]:
train_df.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone,survived
692,3,male,NaN,0,0,56.4958,S,Third,man,True,NaN,Southampton,True,1
481,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,True,0
527,1,male,NaN,0,0,221.7792,S,First,man,True,C,Southampton,True,0
855,3,female,18.0,0,1,9.3500,S,Third,woman,False,NaN,Southampton,False,1
801,2,female,31.0,1,1,26.2500,S,Second,woman,False,NaN,Southampton,False,1

In [42]:
test_df.head()

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alone,survived
565,3,male,24.0,2,0,24.1500,S,Third,man,True,NaN,Southampton,False,0
160,3,male,44.0,0,1,16.1000,S,Third,man,True,NaN,Southampton,False,0
553,3,male,22.0,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,True,1
860,3,male,41.0,2,0,14.1083,S,Third,man,True,NaN,Southampton,False,0
241,3,female,NaN,1,0,15.5000,Q,Third,woman,False,NaN,Queenstown,False,1

In [43]:
train_df.to_csv("titanic_train_raw.csv",index= False)
test_df.to_csv("titanic_test_raw.csv",index= False)