In [2]:
import pandas as pd
s = pd.Series([10, 20, 30, 40, 50],name ="Marks")

print(s)
print("Mean value of the series is",s.mean())

0    10
1    20
2    30
3    40
4    50
Name: Marks, dtype: int64
Mean value of the series is 30.0

**DataFrame(2D Data)**

In [ ]:
data ={
    "Name": ["Alice","Bob","Charlie","David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 91, 78, 88]
}

data_frame = pd.DataFrame(data)

print(data_frame)

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

In [18]:
data_frame.to_csv("data_sample.csv",index= False )

**Read Data From a CSV File**

In [3]:
diabetes_df = pd.read_csv("diabetes.csv")
diabetes_df.shape
diabetes_df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='str')

In [16]:
diabetes_df.head()
diabetes_df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [5]:
df = pd.read_csv("data_sample.csv")
df

      Name  Age  Score
0    Alice   24     85
1      Bob   27     91
2  Charlie   22     78
3    David   32     88

***Selecting the Data***

In [9]:
print(df[["Name","Age"]])
print(df.iloc[1])

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3    David   32
Name     Bob
Age       27
Score     91
Name: 1, dtype: object

In [ ]:
df["City"] = ["New York","Boston","Toronto","Queens"]
df["Score_Percentage"]= df["Score"]/100 * 100
df

      Name  Age  Score      City  Score_Percentage
0    Alice   24     85  New York              85.0
1      Bob   27     91    Boston              91.0
2  Charlie   22     78   Toronto              78.0
3    David   32     88    Queens              88.0

**Descriptive Statistics**