In [ ]:
import pandas as pd
import numpy as np
df1 = pd.DataFrame({"c1": [10, 11, 23, 45], "c2": [45, 56, 67, 87], "c3": [12, 34, 56, 78]}, index=[11, 12, 13, 14])

In [ ]:
df2 = pd.DataFrame({"c1": [40, 11, 23, 45], "c2": [4, 56, 67, 87], "c3": [123, 34, 56, 78]}, index=[15, 16, 17, 18])

In [ ]:
df3=pd.concat([df1,df2])

In [ ]:
df3

    c1  c2   c3
11  10  45   12
12  11  56   34
13  23  67   56
14  45  87   78
15  40   4  123
16  11  56   34
17  23  67   56
18  45  87   78

In [ ]:
l1=[df1,df2]

In [ ]:
df3=pd.concat(l1,keys=['x','y'])
df3.loc["y"]
df3

    c1  c2   c3
15  40   4  123
16  11  56   34
17  23  67   56
18  45  87   78

In [ ]:
dataset=pd.read_csv('/content/loan_small.csv')

In [ ]:
dataset

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
dataset[dataset['Gender'] == "Female"]

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y

In [ ]:
dataset["Gender"][5:10]

5      Male
6      Male
7    Female
8      Male
9      Male
Name: Gender, dtype: object

In [ ]:
dataset

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
dataset["Gender"]=="Female"

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7      True
8     False
9     False
10     True
11    False
12     True
13    False
14    False
15    False
Name: Gender, dtype: bool

In [ ]:
dataset[dataset["Loan_Status"]=="Y"].head()

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y

In [ ]:
dataset[dataset["Loan_Status"]=="Y"][0:5]

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
4,LP001008,Male,NaN,0.0,141.0,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y

In [ ]:
dataset[dataset["Loan_Status"]=="Y"].iloc[:,[1,2,6]]

    Gender  ApplicantIncome Loan_Status
0      NaN           5849.0           Y
2     Male           3000.0           Y
4     Male              NaN           Y
5     Male           5417.0           Y
6     Male           2333.0           Y
8     Male           4006.0           Y
10  Female           3200.0           Y
11    Male           2500.0           Y
12  Female              NaN           Y
14    Male           1299.0           Y
15    Male           4950.0           Y

In [ ]:
dataset[dataset["ApplicantIncome"]>3000]

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y

In [ ]:
dataset[dataset["ApplicantIncome"]>3000][["Gender","ApplicantIncome","LoanAmount"]]

    Gender  ApplicantIncome  LoanAmount
0      NaN           5849.0         NaN
1     Male           4583.0       128.0
5     Male           5417.0       267.0
7   Female           3036.0       158.0
8     Male           4006.0       168.0
9     Male          12841.0       349.0
10  Female           3200.0        70.0
15    Male           4950.0       125.0

In [ ]:
dataset[(dataset["Gender"]=="Male")&(dataset["ApplicantIncome"]>5000)][["Gender","ApplicantIncome","LoanAmount"]]

  Gender  ApplicantIncome  LoanAmount
5   Male           5417.0       267.0
9   Male          12841.0       349.0

In [ ]:
dataset["ApplicantIncome"].min()

1299.0

In [ ]:
dataset["ApplicantIncome"].max()

12841.0

In [ ]:
dataset["ApplicantIncome"].avg()

AttributeError: ignored

In [ ]:
dataset["ApplicantIncome"].mean()

4103.571428571428

In [ ]:
dataset["LoanAmount"].sum()

1832.0

In [ ]:
[dataset["ApplicantIncome"].mean()]&[dataset["LoanAmount"].sum()]

TypeError: ignored

In [ ]:
[dataset["ApplicantIncome"].mean()][[int(dataset["LoanAmount"].sum())]]

<>:1: SyntaxWarning: list indices must be integers or slices, not list; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not list; perhaps you missed a comma?
<ipython-input-12-638ea52a7de2>:1: SyntaxWarning: list indices must be integers or slices, not list; perhaps you missed a comma?
  [dataset["ApplicantIncome"].mean()][[int(dataset["LoanAmount"].sum())]]

TypeError: ignored

In [ ]:
d1=dataset.sort_values(by="ApplicantIncome")

In [ ]:
dataset.sort_values(by="ApplicantIncome",ascending=False)

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
0,LP001002,NaN,5849.0,0.0,NaN,urban,Y
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
10,LP001024,Female,3200.0,700.0,70.0,urban,Y
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
4,LP001008,Male,NaN,0.0,141.0,urban,Y
12,LP001028,Female,NaN,8106.0,NaN,urban,Y

In [ ]:
dataset[dataset["Gender"] == "Male"].sort_values(by=["ApplicantIncome", "LoanAmount"], ascending=[False,True])

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
9,LP001020,Male,12841.0,10968.0,349.0,semi,N
5,LP001011,Male,5417.0,4196.0,267.0,semi,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y
1,LP001003,Male,4583.0,NaN,128.0,semi,N
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
13,LP001029,Male,1853.0,2840.0,114.0,urban,N
14,LP001030,Male,1299.0,1086.0,17.0,semi,Y
4,LP001008,Male,NaN,0.0,141.0,urban,Y

In [ ]:
dataset[dataset["ApplicantIncome"].between(2000, 5000)].sort_values(by=["Gender"], ascending=[False])

,Loan_ID,Gender,ApplicantIncome,CoapplicantIncome,LoanAmount,Area,Loan_Status
1,LP001003,Male,4583.0,NaN,128.0,semi,N
2,LP001005,Male,3000.0,0.0,66.0,NaN,Y
6,LP001013,Male,2333.0,1516.0,NaN,rural,Y
8,LP001018,Male,4006.0,1526.0,168.0,rural,Y
11,LP001027,Male,2500.0,1840.0,109.0,urban,Y
15,LP001032,Male,4950.0,0.0,125.0,semi,Y
3,LP001006,Female,2583.0,2358.0,120.0,semi,NaN
7,LP001014,Female,3036.0,2504.0,158.0,semi,N
10,LP001024,Female,3200.0,700.0,70.0,urban,Y

In [ ]:
ids=[100,101,102,103,104,105,106,107,108,109,110]
ename=["A","B","c","D","E","F","G","H","I","J","K"]
salary=[4000,5000,600,700,800,900,1000,1100,1200,1300,1400]
dept=[10,20,10,30,20,20,30,10,10,10,20]

In [ ]:
empl=pd.DataFrame({"id":ids,"ename":ename,"salary":salary,"dept":dept})

In [ ]:
empl

     id ename  salary  dept
0   100     A    4000    10
1   101     B    5000    20
2   102     c     600    10
3   103     D     700    30
4   104     E     800    20
5   105     F     900    20
6   106     G    1000    30
7   107     H    1100    10
8   108     I    1200    10
9   109     J    1300    10
10  110     K    1400    20

In [ ]:
empl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      11 non-null     int64
 1   ename   11 non-null     object
 2   salary  11 non-null     int64
 3   dept    11 non-null     int64
dtypes: int64(3), object(1)
memory usage: 480.0+ bytes

In [ ]:
empl.dept.unique()

array([10, 20, 30])

In [ ]:
dataset.Loan_Status.unique()

array(['Y', 'N', nan], dtype=object)

In [ ]:
empl.groupby("dept").groups

{10: [0, 2, 7, 8, 9], 20: [1, 4, 5, 10], 30: [3, 6]}

In [ ]:
empl

     id ename  salary  dept
0   100     A    4000    10
1   101     B    5000    20
2   102     c     600    10
3   103     D     700    30
4   104     E     800    20
5   105     F     900    20
6   106     G    1000    30
7   107     H    1100    10
8   108     I    1200    10
9   109     J    1300    10
10  110     K    1400    20

In [ ]:
empl.groupby(["dept",'ename']).groups

{(10, 'A'): [0], (10, 'H'): [7], (10, 'I'): [8], (10, 'J'): [9], (10, 'c'): [2], (20, 'B'): [1], (20, 'E'): [4], (20, 'F'): [5], (20, 'K'): [10], (30, 'D'): [3], (30, 'G'): [6]}

In [ ]:
import webbrowser

In [ ]:
url='https://en.wikipedia.org/wiki/List_of_National_Football_League_records_(individual)'

In [ ]:
webbrowser.open(url)

False

In [ ]:
d={'player':['M S Dhoni','hardhik','rahul','Mohit sharma','Andrerussel','jashprret','virat kohli','rohit sharma'], 'Team':['Chennai Super King','Mumbai indians','kings eleven','GT','kolkata knight riders','Mumbai indians','RCB','Mumbai indians'], 'category':['Batsman','Batsman','Batsman','Bowler','Bowler','Batsman','Batsman','Batsman'], 'Bidprice':[13,11,10,12,7,10,17,15], 'Runs':[4000,2400,3000,1000,1500,3500,5000,3900]}

df=pd.DataFrame(d)

df

         player                   Team category  Bidprice  Runs
0     M S Dhoni     Chennai Super King  Batsman        13  4000
1       hardhik         Mumbai indians  Batsman        11  2400
2         rahul           kings eleven  Batsman        10  3000
3  Mohit sharma                     GT   Bowler        12  1000
4   Andrerussel  kolkata knight riders   Bowler         7  1500
5     jashprret         Mumbai indians  Batsman        10  3500
6   virat kohli                    RCB  Batsman        17  5000
7  rohit sharma         Mumbai indians  Batsman        15  3900

In [ ]:
df[df['category']== "Bowler"]

         player                   Team category  Bidprice  Runs
3  Mohit sharma                     GT   Bowler        12  1000
4   Andrerussel  kolkata knight riders   Bowler         7  1500

In [ ]:
df[df['Team']== "Mumbai indians"]

         player            Team category  Bidprice  Runs
1       hardhik  Mumbai indians  Batsman        11  2400
5     jashprret  Mumbai indians  Batsman        10  3500
7  rohit sharma  Mumbai indians  Batsman        15  3900

In [ ]:
df[(df['Team'] == "Mumbai indians") & (df['Runs'] > 3000)]

         player            Team category  Bidprice  Runs
5     jashprret  Mumbai indians  Batsman        10  3500
7  rohit sharma  Mumbai indians  Batsman        15  3900

In [ ]:
df[(df['Team'] == "RCB") | (df['Team'] =="Chennai Super King")]

        player                Team category  Bidprice  Runs
0    M S Dhoni  Chennai Super King  Batsman        13  4000
6  virat kohli                 RCB  Batsman        17  5000

In [ ]:
print("avg bidprice",df['Bidprice'].mean(),"the average run",df["Runs"].mean())

avg bidprice 11.875 the average run 3037.5

In [ ]:
d=df.sort_values(by="Bidprice", ascending=[True])
d

         player                   Team category  Bidprice  Runs
4   Andrerussel  kolkata knight riders   Bowler         7  1500
2         rahul           kings eleven  Batsman        10  3000
5     jashprret         Mumbai indians  Batsman        10  3500
1       hardhik         Mumbai indians  Batsman        11  2400
3  Mohit sharma                     GT   Bowler        12  1000
0     M S Dhoni     Chennai Super King  Batsman        13  4000
7  rohit sharma         Mumbai indians  Batsman        15  3900
6   virat kohli                    RCB  Batsman        17  5000

In [ ]:
d.tail(1)

        player Team category  Bidprice  Runs
6  virat kohli  RCB  Batsman        17  5000

In [ ]:
r=df.sort_values(by="Runs", ascending=[True])
r.head(1)

         player Team category  Bidprice  Runs
3  Mohit sharma   GT   Bowler        12  1000

In [ ]:
df['player'].count()

8

In [ ]:
df.groupby("Team")['player'].count()

Team
Chennai Super King       1
GT                       1
Mumbai indians           3
RCB                      1
kings eleven             1
kolkata knight riders    1
Name: player, dtype: int64

In [ ]:
i=df.groupby("Team")['Bidprice'].idxmax()
j=df.loc[i,["Team","player","Bidprice"]]
j

                    Team        player  Bidprice
0     Chennai Super King     M S Dhoni        13
3                     GT  Mohit sharma        12
7         Mumbai indians  rohit sharma        15
6                    RCB   virat kohli        17
2           kings eleven         rahul        10
4  kolkata knight riders   Andrerussel         7

In [ ]:

df.groupby("Team")['Runs'].mean()

Team
Chennai Super King       4000.000000
GT                       1000.000000
Mumbai indians           3266.666667
RCB                      5000.000000
kings eleven             3000.000000
kolkata knight riders    1500.000000
Name: Runs, dtype: float64

In [ ]:
s=pd.series(12,13,14,15,null,nan)

AttributeError: ignored

In [ ]:
s = pd.Series([12, 13, 14, 15, None, np.nan])

In [ ]:
s

0    12.0
1    13.0
2    14.0
3    15.0
4     NaN
5     NaN
dtype: float64

In [ ]:
s.isnull()

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

In [ ]:
s.dropna()

0    12.0
1    13.0
2    14.0
3    15.0
dtype: float64

In [ ]:
s

0    12.0
1    13.0
2    14.0
3    15.0
4     NaN
5     NaN
dtype: float64

In [ ]:
s.fillna(100)

0     12.0
1     13.0
2     14.0
3     15.0
4    100.0
5    100.0
dtype: float64

In [ ]:
n=np.nan
df= pd.DataFrame([[40, 11, n, 45],  [4, 56, n, 87], [123, 34, 56, n]])

In [ ]:
df

     0   1     2     3
0   40  11   NaN  45.0
1    4  56   NaN  87.0
2  123  34  56.0   NaN

In [ ]:
df.dropna(how="any")

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []